### ISSUE TITLE
Access OSOD Twitter

### ISSUE THREAD

**Issue by lukefretwell** [OSOD/operations#6]
@grugnog do you have the logins to these for OSOD?

**Comment by grugnog** [comment]
@lukefretwell I do not - I actually wasn't aware these existed (they weren't on the tracking sheet). Not sure who would have these - I see you transferred the DKAN Twitter from Steve Ressler. Of course it's also possible the old passwords from when you set them up still work, or perhaps the accounts are linked to an e-mail you manage?

**Comment by lukefretwell** [comment]
@grugnog thank you. @dafeder I pinged Hoppin to see if he has it. I think we originally shared these in Passpack.

**Comment by andrewhoppin** [comment]
I have them and will send to you directly @lukefretwell because this comment thread is public.

**Comment by lukefretwell** [comment]
@andrewhoppin thank you! @dafeder I now have Gmail and Twitter (MailChimp account expired, but I don't think we need one), so just need to know what your LP email is, so I can share credentials.

**Comment by lukefretwell** [comment]
@dafeder shared with you.
